"""Tests for fledgling-cli — the human-friendly terminal interface.

Runs fledgling-cli as a subprocess against the fledgling repo itself.
Requires duckdb CLI in PATH and a .fledgling-init.sql in the project root
(generated by the test fixture).
"""

import os
import subprocess
import pytest

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CLI = os.path.join(PROJECT_ROOT, "bin", "fledgling-cli")
SQL_DIR = os.path.join(PROJECT_ROOT, "sql")


@pytest.fixture(scope="module")
def cli_init(tmp_path_factory):
    """Generate a .fledgling-init.sql for CLI testing.

    Assembles the init file from local SQL sources (no network needed).
    Returns the path to the init file in a temp directory that mirrors
    the project root (symlinked for file access).
    """
    if not _has_duckdb():
        pytest.skip("duckdb CLI not in PATH")

    workdir = tmp_path_factory.mktemp("cli")
    init_path = workdir / ".fledgling-init.sql"

    # Build a minimal init that loads extensions and macros
    parts = [
        "LOAD read_lines;",
        "LOAD sitting_duck;",
        "LOAD markdown;",
        "LOAD duck_tails;",
        f"SET VARIABLE session_root = '{PROJECT_ROOT}';",
        f"SET VARIABLE conversations_root = '{workdir}';",
        "SET VARIABLE fledgling_version = '0.5.0';",
        "SET VARIABLE fledgling_profile = 'test';",
        "SET VARIABLE fledgling_modules = ['source', 'code', 'docs', 'repo', 'structural', 'help'];",
        f"SET VARIABLE _help_path = '{os.path.join(PROJECT_ROOT, 'SKILL.md')}';",
        f"CREATE OR REPLACE MACRO _resolve(p) AS CASE WHEN p IS NULL THEN NULL WHEN p[1] = '/' THEN p ELSE '{PROJECT_ROOT}/' || p END;",
        f"CREATE OR REPLACE MACRO _session_root() AS '{PROJECT_ROOT}';",
    ]

    # Load SQL files in dependency order
    sql_files = [
        "sandbox.sql", "dr_fledgling.sql",
        "source.sql", "code.sql", "docs.sql", "repo.sql", "structural.sql",
        "conversations.sql", "help.sql",
    ]
    for f in sql_files:
        path = os.path.join(SQL_DIR, f)
        with open(path) as fh:
            sql = fh.read()
        # Strip comment-only lines (same as conftest.load_sql)
        lines = [l for l in sql.split("\n") if not l.strip().startswith("--")]
        parts.append("\n".join(lines))

    init_path.write_text(";\n".join(parts))
    return str(init_path)


def _has_duckdb():
    try:
        subprocess.run(["duckdb", "--version"], capture_output=True, timeout=5)
        return True
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return False


def run_cli(*args, init_path, timeout=30):
    """Run fledgling-cli and return (exit_code, stdout, stderr)."""
    env = os.environ.copy()
    env["FLEDGLING_INIT"] = init_path
    result = subprocess.run(
        [CLI, *args],
        capture_output=True, text=True, timeout=timeout,
        cwd=PROJECT_ROOT, env=env,
    )
    return result.returncode, result.stdout, result.stderr


# ── Special commands ──────────────────────────────────────────────────


class TestHelp:
    def test_help_lists_macros(self, cli_init):
        rc, out, _ = run_cli("help", init_path=cli_init)
        assert rc == 0
        assert "find-definitions" in out or "find_definitions" in out
        assert "recent-changes" in out or "recent_changes" in out

    @pytest.mark.xfail(reason="DuckDB 1.5.0 UTF-8 error rendering help content")
    def test_help_section(self, cli_init):
        rc, out, err = run_cli("help", "workflows", init_path=cli_init)
        assert rc == 0, f"rc={rc}, stderr={err}, stdout={out[:200]}"
        assert "workflows" in out.lower() or "Workflows" in out


class TestInfo:
    def test_info(self, cli_init):
        rc, out, _ = run_cli("info", init_path=cli_init)
        assert rc == 0
        assert "0.5.0" in out
        assert "test" in out  # profile


class TestVersion:
    def test_version(self, cli_init):
        rc, out, _ = run_cli("version", init_path=cli_init)
        assert rc == 0
        assert "0.5.0" in out


class TestQuery:
    def test_raw_sql(self, cli_init):
        rc, out, _ = run_cli("query", "SELECT 42 AS answer", init_path=cli_init)
        assert rc == 0
        assert "42" in out

    def test_query_macro(self, cli_init):
        rc, out, _ = run_cli(
            "query", "SELECT count(*) AS n FROM list_files('**/*.py')",
            init_path=cli_init,
        )
        assert rc == 0
        # Should have at least some python files
        lines = [l for l in out.strip().split("\n") if l.strip() and "n" not in l and "-" not in l]
        assert len(lines) >= 1


# ── File macros ───────────────────────────────────────────────────────


class TestListFiles:
    def test_glob_pattern(self, cli_init):
        rc, out, _ = run_cli("list-files", "tests/*.py", init_path=cli_init)
        assert rc == 0
        assert "test_" in out

    def test_no_results(self, cli_init):
        rc, out, _ = run_cli("list-files", "nonexistent/**/*.xyz", init_path=cli_init)
        assert rc == 0
        assert "file_path" in out  # header only, no data rows


class TestReadSource:
    def test_read_file(self, cli_init):
        rc, out, _ = run_cli("read-source", "tests/conftest.py", init_path=cli_init)
        assert rc == 0
        assert "import" in out

    def test_read_with_lines(self, cli_init):
        rc, out, _ = run_cli(
            "read-source", "tests/conftest.py", "--lines=1-10",
            init_path=cli_init,
        )
        assert rc == 0
        # First 10 lines include the docstring and imports
        assert "fixture" in out.lower() or "import" in out.lower() or "test" in out.lower()


class TestFileLineCount:
    def test_line_counts(self, cli_init):
        rc, out, _ = run_cli("file-line-count", "sql/*.sql", init_path=cli_init)
        assert rc == 0
        assert "sandbox" in out


class TestProjectOverview:
    def test_overview(self, cli_init):
        rc, out, _ = run_cli("project-overview", init_path=cli_init)
        assert rc == 0
        assert "py" in out or "sql" in out


# ── Code macros ───────────────────────────────────────────────────────


class TestFindDefinitions:
    def test_find_in_python(self, cli_init):
        rc, out, _ = run_cli(
            "find-definitions", "tests/conftest.py",
            init_path=cli_init,
        )
        assert rc == 0
        assert "load_sql" in out or "create_resolve" in out

    def test_find_with_name_pattern(self, cli_init):
        rc, out, _ = run_cli(
            "find-definitions", "tests/conftest.py", "%load%",
            init_path=cli_init,
        )
        assert rc == 0
        assert "load" in out.lower()


class TestCodeStructure:
    @pytest.mark.xfail(reason="CTE reference in macro fails through CLI .read path")
    def test_structure(self, cli_init):
        rc, out, _ = run_cli("code-structure", "tests/conftest.py", init_path=cli_init)
        assert rc == 0
        assert "conftest" in out


class TestFindImports:
    def test_imports(self, cli_init):
        rc, out, _ = run_cli("find-imports", "tests/conftest.py", init_path=cli_init)
        assert rc == 0
        assert "import" in out.lower() or "duckdb" in out


class TestFindCalls:
    def test_calls(self, cli_init):
        rc, out, _ = run_cli(
            "find-calls", "tests/conftest.py", "%execute%",
            init_path=cli_init,
        )
        assert rc == 0
        # conftest.py calls con.execute() many times
        assert "execute" in out


class TestComplexityHotspots:
    @pytest.mark.xfail(reason="CTE reference in macro fails through CLI .read path")
    def test_hotspots(self, cli_init):
        rc, out, _ = run_cli(
            "complexity-hotspots", "tests/conftest.py", "5",
            init_path=cli_init,
        )
        assert rc == 0


# ── Doc macros ────────────────────────────────────────────────────────


class TestDocOutline:
    def test_outline(self, cli_init):
        rc, out, _ = run_cli("doc-outline", "SKILL.md", init_path=cli_init)
        assert rc == 0
        assert "Quick Reference" in out or "quick" in out.lower()


class TestReadDocSection:
    @pytest.mark.xfail(reason="DuckDB 1.5.0 UTF-8 error rendering markdown content")
    def test_section(self, cli_init):
        rc, out, _ = run_cli(
            "read-doc-section", "SKILL.md", "workflows",
            init_path=cli_init,
        )
        assert rc == 0
        assert "workflow" in out.lower()


# ── Git macros ────────────────────────────────────────────────────────


class TestRecentChanges:
    def test_recent(self, cli_init):
        rc, out, _ = run_cli("recent-changes", "5", init_path=cli_init)
        assert rc == 0
        assert "hash" in out.lower() or len(out.strip().split("\n")) > 1

    def test_recent_with_columns(self, cli_init):
        rc, out, _ = run_cli(
            "recent-changes", "3", "-c", "hash,message",
            init_path=cli_init,
        )
        assert rc == 0
        assert "hash" in out.lower()
        # Column selection: header should have hash and message but not date
        header = out.strip().split("\n")[0].lower()
        assert "date" not in header


class TestBranchList:
    def test_branches(self, cli_init):
        rc, out, _ = run_cli("branch-list", init_path=cli_init)
        assert rc == 0
        assert "main" in out


class TestFileChanges:
    def test_changes(self, cli_init):
        rc, out, _ = run_cli(
            "file-changes", "HEAD~3", "HEAD",
            init_path=cli_init,
        )
        assert rc == 0


class TestWorkingTreeStatus:
    def test_status(self, cli_init):
        rc, out, _ = run_cli("working-tree-status", init_path=cli_init)
        assert rc == 0


# ── Help macro ────────────────────────────────────────────────────────


class TestHelpMacro:
    """Test the help() macro via the CLI (not the special help command)."""

    def test_help_outline(self, cli_init):
        rc, out, _ = run_cli(
            "query", "SELECT * FROM help()",
            init_path=cli_init,
        )
        assert rc == 0
        assert "section_id" in out.lower() or "quick-reference" in out


class TestDrFledgling:
    def test_dr(self, cli_init):
        rc, out, _ = run_cli("dr-fledgling", init_path=cli_init)
        assert rc == 0
        assert "version" in out
        assert "0.5.0" in out


# ── Output format flags ──────────────────────────────────────────────


class TestOutputFormats:
    def test_csv(self, cli_init):
        rc, out, _ = run_cli(
            "recent-changes", "2", "-f", "csv",
            init_path=cli_init,
        )
        assert rc == 0
        # CSV has commas, no pipes
        assert "," in out
        assert "|" not in out

    def test_json(self, cli_init):
        rc, out, _ = run_cli(
            "recent-changes", "2", "-f", "json",
            init_path=cli_init,
        )
        assert rc == 0
        assert "[" in out or "{" in out

    def test_markdown(self, cli_init):
        rc, out, _ = run_cli(
            "recent-changes", "2", "-f", "markdown",
            init_path=cli_init,
        )
        assert rc == 0
        assert "|" in out


class TestColumnSelection:
    def test_select_columns(self, cli_init):
        rc, out, _ = run_cli(
            "recent-changes", "2", "-c", "hash",
            init_path=cli_init,
        )
        assert rc == 0
        assert "hash" in out.lower()
        # Only one column, shouldn't have message
        lines = [l for l in out.strip().split("\n") if "|" in l and "---" not in l]
        for line in lines:
            # Each row should have at most 2 pipe-separated cells (header + value)
            assert line.count("|") <= 3


# ── Named parameters ─────────────────────────────────────────────────


class TestNamedParams:
    def test_equals_syntax(self, cli_init):
        rc, out, _ = run_cli(
            "doc-outline", "SKILL.md", "--max_lvl=2",
            init_path=cli_init,
        )
        assert rc == 0

    def test_space_syntax(self, cli_init):
        rc, out, _ = run_cli(
            "doc-outline", "SKILL.md", "--max-lvl", "2",
            init_path=cli_init,
        )
        assert rc == 0


# ── PascalCase (MCP tool name) aliases ────────────────────────────────


class TestPascalCase:
    def test_pascal_case_command(self, cli_init):
        rc, out, _ = run_cli("RecentChanges", "3", init_path=cli_init)
        assert rc == 0
        assert "hash" in out.lower()

    @pytest.mark.xfail(reason="CTE reference in macro fails through CLI .read path")
    def test_pascal_code_structure(self, cli_init):
        rc, out, _ = run_cli("CodeStructure", "tests/conftest.py", init_path=cli_init)
        assert rc == 0
        assert "conftest" in out

    def test_pascal_find_definitions(self, cli_init):
        rc, out, _ = run_cli("FindDefinitions", "tests/conftest.py", init_path=cli_init)
        assert rc == 0


# ── Completions ───────────────────────────────────────────────────────


class TestCompletions:
    def test_bash_completions(self, cli_init):
        env = os.environ.copy()
        env["FLEDGLING_INIT"] = cli_init
        result = subprocess.run(
            [CLI, "--completions", "bash"],
            capture_output=True, text=True, timeout=5, env=env,
        )
        assert result.returncode == 0
        assert "complete" in result.stdout
        assert "_fledgling" in result.stdout

    def test_zsh_completions(self, cli_init):
        env = os.environ.copy()
        env["FLEDGLING_INIT"] = cli_init
        result = subprocess.run(
            [CLI, "--completions", "zsh"],
            capture_output=True, text=True, timeout=5, env=env,
        )
        assert result.returncode == 0
        assert "compdef" in result.stdout


# ── Init resolution ───────────────────────────────────────────────────


class TestInitResolution:
    def test_missing_init_errors(self):
        """No init file → helpful error message."""
        if not _has_duckdb():
            pytest.skip("duckdb CLI not in PATH")
        env = os.environ.copy()
        env.pop("FLEDGLING_INIT", None)
        result = subprocess.run(
            [CLI, "info"],
            capture_output=True, text=True, timeout=5,
            cwd="/tmp", env=env,
        )
        assert result.returncode == 1
        assert "no fledgling init file found" in result.stderr.lower()

    def test_env_var_override(self, cli_init):
        """FLEDGLING_INIT takes precedence."""
        rc, out, _ = run_cli("info", init_path=cli_init)
        assert rc == 0
        assert "0.5.0" in out


# ── Error handling ────────────────────────────────────────────────────


class TestErrors:
    def test_nonexistent_macro(self, cli_init):
        rc, out, err = run_cli("nonexistent-command", init_path=cli_init)
        assert rc != 0

    def test_no_args_shows_help(self, cli_init):
        rc, out, _ = run_cli(init_path=cli_init)
        assert rc == 0
        assert "find-definitions" in out or "find_definitions" in out
